### ISSUE TITLE
Support Open Graph Protocol standards

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/metatag#28] opened 2018-09-20 13:14 UTC
This module doesn't output the correct code for Open Graph Protocol standard metatags. Namely it should output:

- The 'property' attribute for the `meta` tag (e.g. `<meta property="og:title" content="The Rock" />` (it currently outputs the 'name' attribute instead))
- The 'prefix' attribute for the `html` tag (e.g. `<html prefix="og: http://ogp.me/ns#">`)

These examples come from: http://ogp.me/

**Comment by ghost** [comment] 2018-09-20 13:47
Added PR.

**Comment by jenlampton** [comment] 2019-08-15 02:54
Nice, thanks for the PR!

**Comment by jackaponte** [comment] 2019-09-09 18:44
Thanks for filing this PR, @BWPanda; I encountered these issues myself! Since there hasn't been a new release of this module I'm going to try to patch my site from your PR.

**Comment by jackaponte** [comment] 2019-09-09 18:46
To be a bit more clear, in the module's current state, the `og:image` property doesn't get read by Facebook Open Graph at all.

**Comment by jenlampton** [comment] 2019-09-09 19:01
@jackaponte  This PR has been merged and should be included in the latest release. Are you still having problems after updating to latest stable?

**Comment by jackaponte** [comment] 2019-09-09 19:34
Ah, whoops, thanks for that heads up Jen--somehow I missed that a new stable release was out! Updating fixed that problem.

**Comment by jenlampton** [comment] 2020-10-20 19:11
This caused regressions in a handful of the other metatags, since it changed all of them from `name` to `property`. I expect only some of them need to be changed, so revering that change to re-evaluate.

**Comment by indigoxela** [comment] 2020-10-22 07:59
The regression gets fixed in this [follow-up](https://github.com/backdrop-contrib/metatag/issues/56). This issue here could get closed by someone with sufficient permissions.

**Closed as completed** 2022-08-02 23:23 UTC
